name: Deploy to VPS
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.7.0
        with:
          host: 62.72.13.48
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd inventoryiitbbs
            git pull origin main
            npm install
            npm run build
            pm2 restart inventory-iitbbs